# configuration for develop and master branch

-
  branches:
    only:
      - develop
      - master

  skip_tags: true
  image: Visual Studio 2019 Preview
  configuration: Release
  platform: Any CPU
  test: off

  pull_requests:
    do_not_increment_build_number: false

  # Install dotnet core 3.0 latest (alpha!!), as this is not provided on AppVeyor yet
  install:
    # - ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe'    
    # - ps: Start-Process .\dotnet-sdk-latest-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
    - ps: Start-FileDownload 'https://download.visualstudio.microsoft.com/download/pr/31b5b67f-b787-4f73-a728-5ec61f10a4de/be6430bcd9a62f610cd9f12f8cc2c736/dotnet-sdk-3.0.100-preview3-010431-win-x64.exe'
    - ps: Start-Process .\dotnet-sdk-3.0.100-preview3-010431-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait


  build_script:
    - ps: .\build.ps1 -Target CI -Verbosity Verbose

  after_build:
    - ps: gci -Filter *.trx -Path .\TestResults\ | % { (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $_.FullName)) }

  artifacts:
    - path: \bin\package\*.*

  nuget:
    disable_publish_on_pr: true

  notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/855da764a995f5aa1a24
      on_build_success: true
      on_build_failure: true
      on_build_status_changed: false