# http://www.appveyor.com/docs/appveyor-yml

# configuration for develop/CI branch
-
  branches:
    only:
      - develop

  version: 5.0.0-dev{build}
  configuration: Release

  init:
    - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version.Remove($env:appveyor_build_version.IndexOf("-dev") + "-dev".Length))$($env:appveyor_build_number.PadLeft(4, '0'))"

  # Install scripts. (runs after repo cloning)
  install:
    - cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

  before_build:
    - cmd: msbuild Fluent.Ribbon.msbuild /target:Restore /v:m /nologo

  build_script:
    - msbuild Fluent.Ribbon.msbuild /target:Build /v:m /nologo

  after_build:
    - cmd: msbuild Fluent.Ribbon.msbuild /target:RunTests /v:m /nologo
    - cmd: msbuild Fluent.Ribbon.msbuild /target:RunPack /v:m /nologo
    - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))

  artifacts:
    - path: Publish\**\*.nupkg
      name: NuGet
  
    - path: Publish\**\*.zip
      name: zip

  assembly_info:
    patch: true
    file: Shared\GlobalAssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/855da764a995f5aa1a24
      on_build_success: true
      on_build_failure: true
      on_build_status_changed: false

# configuration for master/CI branch
-
  branches:
    only:
      - master

  version: 4.0.3.{build}
  configuration: Release

  # Install scripts. (runs after repo cloning)
  install:
    - nuget restore

  build:
    verbosity: minimal

  after_build:
    - cmd: Tools\GitLink.exe . -u https://github.com/fluentribbon/Fluent.Ribbon
    - cmd: nuget pack Fluent.Ribbon.nuspec -Version %appveyor_build_version% -Properties Configuration=%configuration%
    - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

  assembly_info:
    patch: true
    file: Shared\GlobalAssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

  artifacts:
    - path: build/bin
      name: Fluent.Ribbon.$(appveyor_build_version)
      type: zip

  notifications:
    - provider: Webhook
      url: https://webhooks.gitter.im/e/855da764a995f5aa1a24
      on_build_success: true
      on_build_failure: true
      on_build_status_changed: false